config/routes.rb
Rails.application.routes.draw do
    
    resources :users, only: [:new, :create, :validate, :update, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :posts, except: [:show]
    
    get '/' => 'home#index'
    get 'search/search'
    get 'users/show' => 'users#show'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
    has_and_belongs_to_many :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :timeslots
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    add_flash_types :danger, :info, :warning, :success
    protect_from_forgery prepend: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def show
    @user = User.find(session[:user_id])
    @start = @user.start_date
    @end = @user.end_date
    @span = @end - @start
    @passed = Date.today - @start
    @progress = @passed.to_i * 20 / @span.to_i
    
    
    @post_progress = Hash.new
    
    (0...Post.all.length).each do |i|
      @post_progress[i] = (Post.all[i].created_at.to_date - @start).to_i * 20 / @span.to_i
    end
    
    @significant = Array(@post_progress.values) + Array(@progress)
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  end
  
  def new
    @posts = Post.all.reverse
    @user = User.find(session[:user_id])
    @start = @user.start_date
    @end = @user.end_date
    @span = @end - @start
    @passed = Date.today - @start
    @progress = @passed.to_i * 20 / @span.to_i
    
    
    @post_progress = Hash.new
    
    (0...Post.all.length).each do |i|
      @post_progress[i] = (Post.all[i].created_at.to_date - @start).to_i * 20 / @span.to_i
    end
    
    @significant = Array(@post_progress.values) + Array(@progress)
  end
  
  def create
    post = Post.new(user_id: current_user.id, title: params[:title], content: params[:content])
    post.save
    redirect_to new_post_path
  end
  
  def edit
    @posts = Post.all.reverse
    @user = User.find(session[:user_id])
    @start = @user.start_date
    @end = @user.end_date
    @span = @end - @start
    @passed = Date.today - @start
    @progress = @passed.to_i * 20 / @span.to_i
    
    @post_progress = Hash.new
    
    (0...Post.all.length).each do |i|
      @post_progress[i] = (Post.all[i].created_at.to_date - @start).to_i * 20 / @span.to_i
    end
    
    @significant = Array(@post_progress.values) + Array(@progress)
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    redirect_to posts_path if @post.user_id != current_user.id
    
    @post.title = params[:title]
    @post.content = params[:content]
    
    if @post.save
      redirect_to new_post_path
    else
      render :edit
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    redirect_to new_post_path if @post.user_id != current_user.id
    
    @post.destroy
    redirect_to new_post_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:search]
      @users = User.where('teamname LIKE ?', "%#{params[:search]}%")
    else
      @users = User.all
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      login(user)
      redirect_to '/'
      flash[:success] = '성공적으로 로그인되었습니다.'
    else
      redirect_to new_session_path, danger: '잘못된 이메일/비밀번호입니다.'
    end
  end
  
  def destroy
    logout
    redirect_to '/'
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
    def index
        @user = User.find(session[:user_id])
        @timeslot = Timeslot.all
    end
    
    def create
        @user = User.find(session[:user_id])
        @timeslot = @user.timeslot.create(timeslot_params)
        redirect_to timeslots_path
    end

    private
        def timeslot_params
            params.require(:timeslot).permit(:slot)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user
      redirect_to new_user_path, danger: '이미 가입된 이메일입니다.'
    else
      @user = User.new(user_params)
      @user.save
      redirect_to new_session_path, success: '가입완료되었습니다.'
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(users_params)
    redirect_to users_show_path
  end
  
  def timeslotize
    @user = User.find(session[:user_id])
  end
  
  def show
    @posts = Post.all.reverse
    @user = User.find(session[:user_id])
    @start = @user.start_date
    @end = @user.end_date
    @span = @end - @start
    @passed = Date.today - @start
    @progress = @passed.to_i * 20 / @span.to_i
    
    
    @post_progress = Hash.new
    
    (0...Post.all.length).each do |i|
      @post_progress[i] = (Post.all[i].created_at.to_date - @start).to_i * 20 / @span.to_i
    end
    
    @significant = Array(@post_progress.values) + Array(@progress)
  end
  
  private
    def user_params
      params.permit(:email, :password, :password_confirmation, :teamname, :start_date, :end_date)
    end
    
    def users_params
      params.require(:user).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        end
        return @current_user
    end
    
    def user_signed_in?
        return !current_user.nil?
    end
    
    def logout
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="left_nav_bar" id="home_nav">
    <%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg"), '/' %>
    <ul class="left_top_nav">
        <hr>
        <a href="#anchor1"><li class="left_top_nav_3">About</li></a>
        <hr>
        <% if user_signed_in? %>
            <a href="users/show"><li class="left_top_nav_3">시간표</li></a>
            <hr>
            <a href="posts/new"><li class="left_top_nav_3">회의록</li></a>
        <% else %>
            <a href="users/new"><li class="left_top_nav_3">팀 생성</li></a>
            <hr>
            <a href="search/search"><li class="left_top_nav_3">팀 검색</li></a>
        <% end %>
        <hr>
    </ul>
    <ul class="left_bottom_nav" id="home_left_bottom_nav">
        <hr>
        <% if user_signed_in? %>
          <li><%= link_to '로그아웃', session_path(current_user), method: 'delete'  %></li>
        <% else %>
          <li><%= link_to '로그인', new_session_path %></li>
        <% end %>
        <hr>
    </ul>
</div>

<div class="Rectangle" id="anchor2">
    <div id="login">
        <% if user_signed_in? %>
          <%= current_user.teamname %>
        <% else %>
          <%= link_to '로그인', new_session_path %>
        <% end %>
    </div>

    <div class="signin-home">
        <div id="signin-home"><%= link_to '팀 생성', new_user_path %></div>
    </div>
</div>

<div>
    <div class="main_sentence" id="home_main_sentence">
      [<span class="blue">버스타자</span>]가 여러분의 <span class="blue">팀플</span>을 도와드리겠습니다.
    </div>
    <div class="sub_sentence" id="home_sub_sentence">“버스타자와 함께 팀플 모임 시간과 회의록을<br>효과적으로 관리해보세요.”</div>
    <div>
        <%= image_tag("bustaja_background.png", class: "illustration") %>
    </div>
</div>

<section class="blue_box" id="anchor1">
    <div class="overview">
        버스타자 둘러보기
    </div>
    <div class="container">
        <%= image_tag("search-solid.svg", class: "pictogram-1") %>
        <%= image_tag("table-solid.svg", class: "pictogram-2") %>
        <%= image_tag("file-alt-solid.svg", class: "pictogram-3") %>
        <%= image_tag("bell-solid.svg", class: "pictogram-4") %>
    </div>
    <div class="below">
        <div class="below_pictogram1">
            <p class="team_management">팀 검색</p>
            <p class="timetable">시간표</p>
        </div>
    
        <div class="below_pictogram2">
            <p class="discussion">회의록</p>
            <p class="notification">자동 알림</p>
        </div>
    </div>
    <div class="container2">
        <p class="description-a">팀 검색 기능으로 내가<br>속한 팀플 페이지를<br>찾아보세요.</p>
        <p class="description-b">안 되는 시간을 선택하여 팀플 모임 시간을 쉽게<br>정할 수 있습니다.</p>
        <p class="description-c">회의록을 작성하고 이전 작성 회의록을<br>한 눈에 모아보세요.</p>
        <p class="description-d">팀플 시작일과 마감일을 설정해보세요.<br>버스타자가 자동으로<br>경과를 알려드립니다.</p>
    </div>
</section>

<div class="footer">
    <%= image_tag("mainpagebus.png", class: "mainpagebus") %>
</div>

<div class="credit">
    <div>Icons are licensed by <a href="https://fontawesome.com//" title=“Font Awesome”><span id="credit_black">Font Awesome</span></a> and changes are made</div>
    <div id="credit_name">Copyright © 2019, 공채린 박성우 우지명 임지원 홍유진</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bustaja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="hidden" id="wrapper">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name %>'>
          <%= msg %>
        </div>
      <% end %>
    </div>
  </body>
  
  <script>
    $(document).ready(function() {
      setTimeout(function() {
        $('#wrapper').fadeOut("slow", function() {
          $(this).remove();
        })
      }, 1500);
    });
  </script>
</html>

app/views/posts/edit.html.erb
<div class="left_nav_bar">
    <%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg"), '/' %>
    <ul class="left_top_nav">
        <hr>
        <li class="left_top_nav_3"><%= link_to '시간표', users_show_path %></li>
        <hr>
        <li class="left_top_nav_3"><%= link_to '회의록', new_post_path %></li>
        <hr>
    </ul>
    <ul class="left_bottom_nav">
        <hr>
        <li><%= link_to '로그아웃', session_path(current_user), method: 'delete'  %></li>
        <hr>
    <ul>
</div>

<div class="Rectangle_bus">
    <div class ="top-bar">
        <table id='busmove'>
            <tbody>
                <tr class="row">
                    <% for i in (1..20) %>
                        <% if i==@progress %>
                            <td class="one"></td>
                            <% next %>
                        <% elsif @significant.include?(i) %>
                            <td class="two"><%= link_to posts_show_path do %><%= image_tag 'bus-stop.svg' %><% end %></td>
                        <% else %>
                            <td></td>
                        <% end %>
                    <% end %>
                    <div id="top_flag"><%= image_tag "flag.png"%></div>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<div class="main_sentence2_record">
  <span class="blue">회의록</span>을 저장하고,<br><span class="blue">지난 회의록</span>을 확인해보세요.
</div>

<div id="anchor2" class="container-post">
    <!--지난 회의록 목록-->
    <div class="date_nav">
        <p class="past">지난 회의록</p>
        <% @posts.each do |post| %>
            <% if post.user.teamname != current_user.teamname %>
                <% next %>
            <% else %>
                <ul>
                    <li>
                        <p class="date"><%= link_to post.title, edit_post_path(post) %></p>
                        <a rel="nofollow" data-method="delete" href="/posts/<%=post.id%>"><button class="delete">&times;</button></a>
                    </li>
                </ul>
            <% end %>
        <% end %>
    </div>
    
    <div class="textfield">
        <%= form_tag post_path(@post), method: "patch" do %>
        <input type="hidden" name="id" value="<%= @post.id %>">
        <div class="upper">
            <%= text_field_tag :title, @post.title, class: "removeOnFocus", placeholder: "제목을 입력해주세요" %>
            <%= button_tag "저장", {id: "save"} %>
            
        </div>
        
        <div class="notepad">
            <%= text_area_tag :content, @post.content, id: "field", placeholder: "회의 내용을 수정해주세요" %>
        <% end %>
        </div>
    </div>
</div>

<div class="timetable_credit">
    <div>Icons made by <a href="https://www.freepik.com/" title="Freepik" id="credit_black">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
    <div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons" id="credit_black">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
</div>

app/views/posts/new.html.erb
<div class="left_nav_bar">
    <%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg"), '/' %>
    <ul class="left_top_nav">
        <hr>
        <li class="left_top_nav_3"><%= link_to '시간표', users_show_path %></li>
        <hr>
        <li class="left_top_nav_3"><%= link_to '회의록', new_post_path %></li>
        <hr>
    </ul>
    <ul class="left_bottom_nav">
        <hr>
        <li><%= link_to '로그아웃', session_path(current_user), method: 'delete'  %></li>
        <hr>
    <ul>
</div>

<div class="Rectangle_bus">
    <div class ="top-bar">
        <table id='busmove'>
            <tbody>
                <tr class="row">
                    <% for i in (1..20) %>
                        <% if i==@progress %>
                            <td class="one"></td>
                            <% next %>
                        <% elsif @significant.include?(i) %>
                            <td class="two"><%= link_to posts_show_path do %><%= image_tag 'bus-stop.svg' %><% end %></td>
                        <% else %>
                            <td></td>
                        <% end %>
                    <% end %>
                    <div id="top_flag"><%= image_tag "flag.png"%></div>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="main_sentence2_record">
  <span class="blue">회의록</span>을 저장하고,<br><span class="blue">지난 회의록</span>을 확인해보세요.
</div>

<div id="anchor2" class="container-post">
    <!--지난 회의록 목록-->
    <div class="date_nav">
        <p class="past">지난 회의록</p>
        <% @posts.each do |post| %>
            <% if post.user.teamname != current_user.teamname %>
                <% next %>
            <% else %>
                <ul>
                    <li>
                        <p class="date"><%= link_to post.title, edit_post_path(post) %></p>
                        <a rel="nofollow" data-method="delete" href="/posts/<%=post.id%>"><button class="delete">&times;</button></a>
                    </li>
                </ul>
            <% end %>
        <% end %>
    </div>
    
    <!--새 글 작성하기-->
    <div class="textfield">
        <%= form_tag posts_path do %>
        <div class="upper">
            <%= text_field_tag :title, nil, class: "removeOnFocus", placeholder: "제목을 입력해주세요" %>
            <%= button_tag "저장", {id: "save"} %>
        </div>
        
        <div class="notepad">
            <%= text_area_tag :content, nil, id: "field", placeholder: "회의 내용을 작성해주세요" %>
        <% end %>
        </div>
    </div>
</div>

<div class="timetable_credit">
    <div>Icons made by <a href="https://www.freepik.com/" title="Freepik" id="credit_black">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
    <div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons" id="credit_black">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
</div>

app/views/search/search.html.erb
<%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg-pagever"), '/' %>
<div class="login">
    <p>팀 검색</p>
</div>
<div id="searchbar">
    <%= form_tag(search_search_path, method: :get, id: "form") do %>
        <%= text_field_tag :search, params[:search], size: "35", id: "search_input" %>
        <%= submit_tag "검색", id: "search-button" %>
    <% end %>
    <%= form_tag(search_search_path, method: :get, id: "form") do %>
        <%= submit_tag "초기화", id: "search-button" %>
    <% end %>
</div>

<table id="usertable-home">
    <tbody>
        <tr>
            <th id="header">아이디</th>
            <th id="header">팀 이름</th>
            <th id="header">시작일</th>
            <th id="header">종료일</th>
            <th id="header"> </th>
        </tr>
        <% for user in @users %>
            <tr>
                <td id="tableitem"><%= user.email %></td>
                <td id="tableitem"><%= user.teamname %></td>
                <td id="tableitem"><%= user.start_date %></td>
                <td id="tableitem"><%= user.end_date %></td>
                <td id="tableitem_login"><%= link_to '로그인', new_session_path %></td>
            </tr>
        <% end %>
    </tbody>    
</table>

app/views/users/new.html.erb
<%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg-pagever"), '/' %>
<div class="signin">
    <p>팀 생성</p>
</div>
<div id="warning">
    <p>*표시는 필수 입력 항목입니다</p>
</div>
<%= form_for :user, url: users_path do |f| %>
    <table>
        <tbody>
            <tr>
                <th class="inputitem">이메일<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="email" name="email" placeholder="bustaja@gmail.com" required></td>
            </tr>
            <tr>
                <th class="inputitem">팀이름<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="text" name="teamname" placeholder="버스타자" required></td>
            </tr>
            <tr>
                <th class="inputitem">비밀번호<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="password" name="password" required></td>
            </tr>
            <tr>
                <th class="inputitem">비밀번호 확인<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="password" name="password_confirmation" required></td>
            </tr>
            <tr>
                <th class="inputitem">출발 날짜<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="date" name="start_date" value="2019-01-01" required></td>
            </tr>
            <tr>
                <th class="inputitem">도착 날짜<sup>*</sup></th>
                <td class="login_td"><input class="inputbox" type="date" name="end_date" value="2019-01-01" required></td>
            </tr>
        </tbody>
    </table>
    <div id="regbutton"><button id="button" type="submit">가입하기</button></div>
<% end %>

<script>
    // input text 클릭 시 기본 값 사라지는 함수
        $(document).ready(function(){
        $('.inputbox').each(function()
        {this.data = new Object(); //TODO don't overwrite previous data
        this.data.value = this.value;
        $(this).focus(function(){
          if (this.value == this.data.value)
              this.value = '';});
        $(this).blur(function(){
          if (this.value == '')
              this.value = this.data.value;});});});
</script>

<script src="jquery-3.4.1.min.js"></script>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width">
    <title></title>
    <link rel="stylesheet" type="text/css" href="timeslot.scss"/>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
    <script src="jquery-3.4.1.min.js"></script>

  </head>
      
  <body id="time_body">
      
    <div class="left_nav_bar">
        <%= link_to image_tag("logo_3.png", class: "illustration_nav", id: "logoimg"), '/' %>
        <ul class="left_top_nav">

        <hr>
        <li class="left_top_nav_3"><%= link_to '시간표', users_show_path %></li>
        <hr>
        <li class="left_top_nav_3"><%= link_to '회의록', new_post_path %></li>
        <hr>
        </ul>
        <ul class="left_bottom_nav">
        <hr>
        <li><%= link_to '로그아웃', session_path(current_user), method: 'delete'  %></li>
        <hr>
        <ul>
    </div>
    <div class="main_sentence">
        안 되는 시간을 클릭하여<br><span class="blue">회의 시간</span>을 정해보세요.
    </div>
    
    <div class="Rectangle_bus">
        <div class ="top-bar">
            <table id='busmove'>
                <tbody>
                    <tr class="row">
                        <% for i in (1..20) %>
                            <% if i==@progress %>
                                <td class="one"></td>
                                <% next %>
                            <% else %>
                                <td></td>
                            <% end %>
                        <% end %>
                        <div id="top_flag"><%= image_tag "flag.png"%></div>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

  
    
    <%= form_for(@user) do |f| %>



      <div class="tablebox">
        <table id="time_table">
          <tbody id="time_tbody">
            <tr>
              <td class="timeTableCellDay"></td>
              <td class="timeTableCellDay">월</td>
              <td class="timeTableCellDay">화</td>
              <td class="timeTableCellDay">수</td>
              <td class="timeTableCellDay">목</td>
              <td class="timeTableCellDay">금</td>
              <td class="timeTableCellDay">토</td>
              <td class="timeTableCellDay">일</td>
            </tr>


            <tr id='line1'>
              <td class="timeTableCellTime">9:00</td>
              <% Timeslot.all[0,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_1"></div></label></td>
              <% end %>
            </tr>

            <tr id='line2'>
              <td class="timeTableCellTime">10:00</td>
              <% Timeslot.all[7,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_1"></div></label></td>
              <% end %>
            </tr>

            <tr id='line3'>
              <td class="timeTableCellTime">11:00</td>
              <% Timeslot.all[14,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_2"></div></label></td>
              <% end %>
            </tr>

            <tr id='line4'>
              <td class="timeTableCellTime">12:00</td>
              <% Timeslot.all[21,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_2"></div></label></td>
              <% end %>
            </tr>

            <tr id='line5'>
              <td class="timeTableCellTime">13:00</td>
              <% Timeslot.all[28,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_3"></div></label></td>
              <% end %>
            </tr>

            <tr id='line6'>
              <td class="timeTableCellTime">14:00</td>
              <% Timeslot.all[35,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_3"></div></label></td>
              <% end %>
            </tr>

            <tr id='line7'>
              <td class="timeTableCellTime">15:00</td>
              <% Timeslot.all[42,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_4"></div></label></td>
              <% end %>
            </tr>

            <tr id='line8'>
              <td class="timeTableCellTime">16:00</td>
              <% Timeslot.all[49,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_4"></div></label></td>
              <% end %>
            </tr>

            <tr id='line9'>
              <td class="timeTableCellTime">17:00</td>
              <% Timeslot.all[56,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_5"></div></label></td>
              <% end %>
            </tr>

            <tr id='line10'>
              <td class="timeTableCellTime">18:00</td>
              <% Timeslot.all[63,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_5"></div></label></td>
              <% end %>
            </tr>

            <tr id='line11'>
              <td class="timeTableCellTime">19:00</td>
              <% Timeslot.all[70,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_6"></div></label></td>
              <% end %>
            </tr>

            <tr id='line12'>
              <td class="timeTableCellTime">20:00</td>
              <% Timeslot.all[77,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_6"></div></label></td>
              <% end %>
            </tr>

            <tr id='line13'>
              <td class="timeTableCellTime">21:00</td>
              <% Timeslot.all[84,7].each do |timeslot| %>
                <td><label class="contain_timeslot"><%= check_box_tag "user[timeslot_ids][]", timeslot.id, @user.timeslot_ids.include?(timeslot.id) %><div class="checkmark" id="color_7"></div></label></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <%= f.submit "저장" %>
      </div>
        
    <% end %>
    
    <div class="timetable_credit">
        <div>Icons made by <a href="https://www.freepik.com/" title="Freepik" id="credit_black">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
        <div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons" id="credit_black">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
  </div>

  </body>
</html>